language: scala
sudo: false
jdk:
  - oraclejdk8
before_install:
  - gem install bundler
rvm:
  - 2.2.4
cache:
  bundler: true
  directories:
    - $HOME/.ivy2/cache
    - node_modules
    - ui/node_modules
    - ui/jspm_packages
node_js:
  - "node"
before_script:
  - bundle install
  - npm install -g gulp jspm
  - npm install
script:
  - sbt ";gulp;test"
